services:
  - type: web
    name: times-and-more
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --worker-class sync
    envVars:
      - key: FLASK_ENV
        value: production
